package com.bss.domain.outbox;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class OutboxEventTest {

    @Test
    @DisplayName("Should create OutboxEvent with correct initial state")
    void shouldCreateOutboxEventWithCorrectInitialState() {
        // Arrange
        String aggregateType = "Transfer";
        String aggregateId = "123";
        String eventType = "TransferRequested";
        String payload = "{\"amount\": 100}";

        // Act
        OutboxEvent event = new OutboxEvent(aggregateType, aggregateId, eventType, payload);

        // Assert
        assertNull(event.getId()); // ID is generated by JPA
        assertEquals(aggregateType, event.getAggregateType());
        assertEquals(aggregateId, event.getAggregateId());
        assertEquals(eventType, event.getEventType());
        assertEquals(payload, event.getPayload());
        assertEquals(OutboxEventStatus.UNPROCESSED, event.getStatus());
        assertEquals(0, event.getRetryCount());
        assertNotNull(event.getCreatedAt());
        assertNull(event.getLockedAt());
    }

    @Test
    @DisplayName("Should increment retry count")
    void shouldIncrementRetryCount() {
        // Arrange
        OutboxEvent event = new OutboxEvent("Transfer", "123", "TransferRequested", "{}");
        assertEquals(0, event.getRetryCount());

        // Act
        event.incrementRetryCount();

        // Assert
        assertEquals(1, event.getRetryCount());
    }

    @Test
    @DisplayName("Should handle failure: increment retry count and reset lock")
    void shouldHandleFailureIncrementRetryAndResetLock() {
        // Arrange
        OutboxEvent event = new OutboxEvent("Transfer", "123", "TransferRequested", "{}");
        event.setLockedAt(LocalDateTime.now());
        event.setStatus(OutboxEventStatus.PROCESSING);
        int maxRetries = 3;

        // Act
        event.handleFailure(maxRetries);

        // Assert
        assertEquals(1, event.getRetryCount());
        assertNull(event.getLockedAt());
        assertEquals(OutboxEventStatus.UNPROCESSED, event.getStatus());
    }

    @Test
    @DisplayName("Should handle failure: mark as FAILED when max retries reached")
    void shouldHandleFailureMarkAsFailedWhenMaxRetriesReached() {
        // Arrange
        OutboxEvent event = new OutboxEvent("Transfer", "123", "TransferRequested", "{}");
        event.setRetryCount(2); // Already retried twice
        int maxRetries = 3;

        // Act
        event.handleFailure(maxRetries); // This is the 3rd retry (retryCount becomes 3)

        // Assert
        assertEquals(3, event.getRetryCount());
        assertNull(event.getLockedAt());
        assertEquals(OutboxEventStatus.FAILED, event.getStatus());
    }

    @Test
    @DisplayName("Should handle failure: mark as FAILED when max retries exceeded")
    void shouldHandleFailureMarkAsFailedWhenMaxRetriesExceeded() {
        // Arrange
        OutboxEvent event = new OutboxEvent("Transfer", "123", "TransferRequested", "{}");
        event.setRetryCount(5);
        int maxRetries = 3;

        // Act
        event.handleFailure(maxRetries);

        // Assert
        assertEquals(6, event.getRetryCount());
        assertEquals(OutboxEventStatus.FAILED, event.getStatus());
    }

    @Test
    @DisplayName("Should update status correctly")
    void shouldUpdateStatus() {
        // Arrange
        OutboxEvent event = new OutboxEvent("Transfer", "123", "TransferRequested", "{}");

        // Act
        event.setStatus(OutboxEventStatus.PROCESSED);

        // Assert
        assertEquals(OutboxEventStatus.PROCESSED, event.getStatus());
    }

    @Test
    @DisplayName("Should update lockedAt correctly")
    void shouldUpdateLockedAt() {
        // Arrange
        OutboxEvent event = new OutboxEvent("Transfer", "123", "TransferRequested", "{}");
        LocalDateTime now = LocalDateTime.now();

        // Act
        event.setLockedAt(now);

        // Assert
        assertEquals(now, event.getLockedAt());
    }
    
    @Test
    @DisplayName("Should set retry count manually")
    void shouldSetRetryCountManually() {
        // Arrange
        OutboxEvent event = new OutboxEvent("Transfer", "123", "TransferRequested", "{}");

        // Act
        event.setRetryCount(10);

        // Assert
        assertEquals(10, event.getRetryCount());
    }
}
